server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/IVR?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数
        max-active: 50
        # 连接池中最大阻塞等待时间
        max-wait: 3000
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小控线连接
        min-idle: 2
    timeout: 5000
